In [4]:
import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns

In [5]:
df = pd.read_csv("../../data/train.csv")

# Question 1
Please show all the information that belongs to the first six passengers. You should have
6 rows each referring to a passenger, and the values of 12 features (columns) for each
passenger.

In [6]:
df.head(6)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q

# Question 2
Please show all the information that belongs to the last six passengers. You should have
6 rows each referring to a passenger, and the values of 12 features (columns) for each
passenger.

In [7]:
df.tail(6)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.125,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.450,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.750,NaN,Q

# Question 3
Please list the attributes (column titles).

In [8]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

# Question 4
Please show the size of the dataset: (the number of passengers only). Do not forget to
write what the output of your script refers to.

In [9]:
len(df)

891

# Question 5
Please check how many missing values there are in the dataset for the columns
“Age”,“Cabin” and “Embarked”. Missing values will have a null value (NaN). Do not
forget to write how many missing values there are for each of these three columns in the
comments.

## missing values of "Age" are

In [10]:
 df["Age"].isnull().sum()

np.int64(177)

## missing values of "Cabin" are

In [11]:
df["Cabin"].isnull().sum()

np.int64(687)

## missing values of "Embarked" are

In [12]:
df["Embarked"].isnull().sum()

np.int64(2)

# Question 6
the age of the youngest passenger

# Question 7
the age of the youngest passenger who survived

# Question 8
the average fare

# Question 9
the age of the oldest passenger who survived\n

# Question 10
the age of the oldest female passenger who survived

# Question 11
children under the age of 10 traveling without their parents

# Question 12
the number of siblings of the passenger who has the highest number of siblings

# Question 13
the most commonly used title

# Question 14
distinct titles are used

# Question 15
the average age of the passengers