In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [46]:
df_titanic = pd.read_csv('train.csv') #reads the data
df_titanic.info() #shows information about the data frame

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

# Question 1

In [47]:
df_titanic[:6] #shows the first 6 data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q

# Question 2

In [48]:
df_titanic[-6:] #shows the last 6 data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.125,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.450,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.750,NaN,Q

# Question 3

In [49]:
list(df_titanic.columns) #shows the column titles

['PassengerId',
 'Survived',
 'Pclass',
 'Name',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Ticket',
 'Fare',
 'Cabin',
 'Embarked']

# Question 4

In [50]:
df_titanic.shape[0] #shows the passengers size of the dataset

891

# Question 5

In [51]:
df_titanic.isna().sum() #shows the number of NaN values of the all columns

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [52]:
df_titanic["Age"].isna().sum() #shows the number of NaN values of the age column

np.int64(177)

In [53]:
df_titanic["Cabin"].isna().sum() #shows the number of NaN values of the cabin column

np.int64(687)

In [54]:
df_titanic["Embarked"].isna().sum() #shows the number of NaN values of the embarked column

np.int64(2)

Age column has 177 NaN values, cabin column has 687 NaN values, embarked column has 2 NaN values.

# Question 6

In [55]:
df_titanic["Age"].min() #shows the age of the youngest passenger

np.float64(0.42)

# Question 7

In [56]:
df_titanic[df_titanic["Survived"]==1]["Age"].min() #shows the age of the youngest passenger who survived

np.float64(0.42)

# Question 8

In [57]:
df_titanic["Fare"].mean() #shows the average fare

np.float64(32.204207968574636)

# Question 9

In [58]:
df_titanic[df_titanic["Survived"]==1]["Age"].max() #shows the age of the oldest passenger who survived

np.float64(80.0)

# Question 10

In [59]:
df_titanic[(df_titanic["Survived"]==1) & (df_titanic["Sex"]=="female")]["Age"].max() #shows the age of the oldest female passenger who survived

np.float64(63.0)

# Question 11

In [60]:
df_titanic[(df_titanic["Age"] < 10) & (df_titanic["Parch"]==0)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
777,778,1,3,"Emanuel, Miss. Virginia Ethel",female,5.0,0,0,364516,12.475,NaN,S

There was a child under the age of 10 traveling without their parents. This may be because there might be a mistake in the data or the baby may have boarded the ship with the babysitter.

# Question 12

In [61]:
df_titanic["SibSp"].max() #shows the number of siblings of the passenger who has the highest number of siblings

np.int64(8)

# Question 13 - 14

In [62]:
df_titanic["Title"] = df_titanic["Name"].apply(lambda x: x.split(',')[1].split(" ")[1]) # split name to get titles
df_titanic.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr.
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs.
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss.
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs.
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr.

In [63]:
df_titanic['Title'].mode()

0    Mr.
Name: Title, dtype: str

In [64]:
df_titanic['Title'].nunique()

17

The most commonly used titleis Mr. and there are 17 distinct titles are used.

# Question 15

In [65]:
df_titanic["Age"].mean()

np.float64(29.69911764705882)